# Generated by Django 5.0.7 on 2024-09-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='cart',
            field=models.TextField(blank=True, default=''),
        ),
    ]
